spring:
  application:
    version: "1.0"
    formatted-version: "(v1.0)"
    name: "Lavalink"
  cloud:
    config:
      enabled: false
server:
  error:
    include-message: NEVER
    include-binding-errors: NEVER
    include-stacktrace: NEVER
    include-exception: false
